
skip_docs
default_platform(:ios)

platform :ios do

  desc "Runs the test target, which executes all the unit tests for each module
  within the SDK"
  lane :unit_tests do
    sh("
      set -o pipefail && xcodebuild \
      -workspace '../PayPal.xcworkspace' \
      -sdk 'iphonesimulator' \
      -configuration 'Debug' \
      -scheme 'UnitTests' \
      -destination 'name=iPhone 12,platform=iOS Simulator' \
      test | xcpretty
      ")
  end

  desc "Runs SwiftLint and returns any errors if our linter rule aren't met"
  lane :lint do
    swiftlint(
      mode: :lint,
      config_file: ".swiftlint.yml",
      raise_if_swiftlint_error: true,
      ignore_exit_status: true,
      strict: true
    )
  end
end
