
skip_docs
default_platform(:ios)

platform :ios do

  desc "Runs UnitTests & code coverage check"
  lane :unit_tests do
    sh("
      set -o pipefail && xcodebuild \
      -workspace '../PayPal.xcworkspace' \
      -sdk 'iphonesimulator' \
      -configuration 'Debug' \
      -scheme 'UnitTests' \
      -destination 'name=iPhone 14,platform=iOS Simulator' \
      test | xcpretty
      ")

    # Ensure the code coverage directory is empty before creating new coverage
    sh("rm -rf coverage")

    # xcov command can't find PayPalCheckout SPM package unless additional resolve is performed
    sh("swift package resolve")

    # Fails unit_tests job if coverage below minimum_coverage_percentage
    xcov(
      scheme: "Demo",
      workspace: "PayPal.xcworkspace",
      output_directory: "fastlane/coverage",
      minimum_coverage_percentage: 80.0
    )
  end

  desc "Runs SwiftLint and returns any errors if our linter rule aren't met"
  lane :lint do
    swiftlint(
      mode: :lint,
      raise_if_swiftlint_error: true,
      strict: true
    )
  end
end
