
skip_docs
default_platform(:ios)

platform :ios do

  desc "Runs the test target, which executes all the unit tests for each module
  within the SDK"
  lane :tests do
    run_tests(
      workspace: "PayPal.xcworkspace",
      device: "iPhone 8",
      scheme: "UnitTests"
    )
  end
end
